name:  BuildDocker

on:

  push:

    branches: [ shiken ]

  pull_request:

    branches: [ shiken ]

jobs:

  build:

   runs-on: ubuntu-20.04

   steps:

      - uses: actions/checkout@master
      - run:  bash exp.sh
      - uses: H1M4N5HU0P/Publish-Docker-Github-Action@master

        with:

          name:  H1M4N5HU0P/AliciaRobot

          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_PASSWORD }}

          dockerfile: Dockerfile

          buildoptions: --force-rm --compress --no-cache --squash

          tags: "shiken"
