name: Black

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Run black
        run: black AliciaRobot
      - name: Create Pull Request
        uses: H1M4N5HU0P/create-pull-request@v3
        with:
          commit-message: Format code using black
          title: Format code.
          body: Format code using black.
          labels: ⚫️ black
          branch: autofix
